# nixpacks.toml
providers = ["node"]

[phases.setup]
  nixPkgs = ["nodejs"]

[phases.install]
  cmds = ["npm ci"]  # Explicitly install dependencies with npm ci

[phases.build]
  cmds = ["npm run build"]  # Runs "robo build"

[start]
  cmd = "npm run start"     # Runs "robo start"